version: "3.7"
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379"
    restart: always
    networks:
      - backend
  app:
    container_name: url_checker_app
    build:
      context: .
      dockerfile: Dockerfile
    image: url_checker_app:latest
    ports:
      - "8000:8000"
    restart: always
    depends_on: 
      - redis
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend
networks:
  backend:    